### ISSUE TITLE
KeyError:"Configuration file contains the following unrecognized options: ['log']

### ISSUE THREAD

**Issue by Anker-Lee** [EducationalTestingService/rstfinder#73] opened 2022-02-18 13:33 UTC
Hello!
When I run the 7th command: `tune_rst_parser rst_discourse_tb_edus_TRAINING_TRAIN.json rst_discourse_tb_edus_TRAINING_DEV.json rst_parsing_model,` 
it gives me the`KeyError`. Anybody can help me to solve this problem?

**Comment by desilinguist** [comment] 2022-02-18 13:38
Ah, this is because rstfinder hasn't been updated to use the new release of the SKLL that recently deprecated some fields. 

I'll work on a fix for this. In the meantime, you can simply downgrade SKLL to v2.5 in your conda environment and things should work again.

**Comment by Anker-Lee** [comment] 2022-02-20 05:36
Thank you very much!
Downgrade SKLL to v2.5 works quite well!
But when I ran the 7th command, 
`tune_rst_parser rst_discourse_tb_edus_TRAINING_TRAIN.json rst_discourse_tb_edus_TRAINING_DEV.json rst_parsing_model`
It ran well at the beginning, but when it came to around 54.872392%, it stopped for a short moment and threw out `concurrent.futures.proess.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending` error. 
Could you please help me out again?

**Comment by desilinguist** [comment] 2022-02-20 05:37
Very strange. I've never seen that error before. Are there any log files created perhaps? If so, please share.

**Comment by Anker-Lee** [comment] 2022-02-20 05:43
`Traceback (most recent call last):
  File "/home/anker/anaconda3/envs/rstenv2/bin/tune_rst_parser", line 11, in <module>
    sys.exit(main())
  File "/home/anker/anaconda3/envs/rstenv2/lib/python3.8/site-packages/rstfinder/tune_rst_parser.py", line 306, in main
    for C_value, results in zip(C_values, all_results):
  File "/home/anker/anaconda3/envs/rstenv2/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/anker/anaconda3/envs/rstenv2/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/anker/anaconda3/envs/rstenv2/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/anker/anaconda3/envs/rstenv2/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

**Comment by Anker-Lee** [comment] 2022-02-20 05:55
> Very strange. I've never seen that error before. Are there any log files created perhaps? If so, please share.

It seems that there was not log files created. Is it possible that it can not work on a virtual machine?

**Comment by desilinguist** [comment] 2022-02-20 05:57
Oh interesting. I’ve never tried it on a VM. That could be it, I’m not sure.

 Is the error reproducible - if you run it again, does it fail again with the same error?
________________________________

**Comment by Anker-Lee** [comment] 2022-02-20 06:03
> Oh interesting. I’ve never tried it on a VM. That could be it, I’m not sure. Is the error reproducible - if you run it again, does it fail again with the same error?
> […](#)

Yes, it is reproducible.

**Comment by desilinguist** [comment] 2022-02-20 06:15
Could you try on a regular machine  if possible and see if you get the same error? 

I'll also try to run it myself.

**Comment by Anker-Lee** [comment] 2022-02-20 06:21
> Could you try on a regular machine if possible and see if you get the same error?
> 
> I'll also try to run it myself.

It seems that memory distributed to the VM was too small, I have redistributed the memory. I will try it again. THANKS A LOT FOR HELPING ME! : )

**Comment by Anker-Lee** [comment] 2022-02-20 06:29
> Could you try on a regular machine if possible and see if you get the same error?
> 
> I'll also try to run it myself.

It does not throw errors at that position! 
Is it normal for the training and featuring process to wait for a while?
It stopped at `INFO: Hyperparameters: C:0.25 ... warm_start: False` for a long time.
It seems that the training process takes quite a long time.

**Comment by Anker-Lee** [comment] 2022-02-20 06:59
> Could you try on a regular machine if possible and see if you get the same error?
> 
> I'll also try to run it myself.

Thanks a lot for your helpful tool!
After `tune_rst_parser rst_discourse_tb_edus_TRAINING_TRAIN.json rst_discourse_tb_edus_TRAINING_DEV.json rst_parsing_model `, it throw out
`ValueError: X has 640 features, but StanderScaler is expecting 74698 features as input.`
I seen the answer in #72, is skill v2.5 still can not work?

**Comment by desilinguist** [comment] 2022-02-28 20:03
Yeah, looks like there’s some incompatibility. I am working on fixing this now.

**Closed as completed** 2022-03-04 14:41 UTC

**Comment by Anker-Lee** [comment] 2022-03-11 01:40
Thanks a lot for helping me!
You are really nice!

**Comment by desilinguist** [comment] 2022-03-11 05:16
You're most welcome!
