### ISSUE TITLE
tune_rst_parser throws ValueError with parameters given in README

### ISSUE THREAD

**Issue by arne-cl** [EducationalTestingService/rstfinder#43] opened 2015-07-13 21:49 UTC
`tune_rst_parser` runs for a while and generates some files in the `working` directory, then throws this error:

``` python
/opt/discourse-parsing# tune_rst_parser rst_discourse_tb_edus_TRAINING_TRAIN.json rst_discourse_tb_edus_TRAINING_DEV.json rst_parsing_model
Traceback (most recent call last):
  File "/usr/local/bin/tune_rst_parser", line 9, in <module>
    load_entry_point('discourseparsing==0.2.1', 'console_scripts', 'tune_rst_parser')()
  File "/usr/local/lib/python3.3/dist-packages/discourseparsing-0.2.1-py3.3.egg/discourseparsing/tune_rst_parser.py", line 214, in main
  File "/usr/lib/python3.3/concurrent/futures/_base.py", line 548, in result_iterator
    yield future.result()
  File "/usr/lib/python3.3/concurrent/futures/_base.py", line 394, in result
    return self.__get_result()
  File "/usr/lib/python3.3/concurrent/futures/_base.py", line 353, in __get_result
    raise self._exception
ValueError: Invalid [Input] parameters: either "train_file" or "train_directory" must be specified in the configuration file.
```

**Comment by aoifecahill** [comment] 2015-07-14 19:51
Can you confirm which version of skll you are using?

**Comment by arne-cl** [comment] 2015-07-14 20:42
I'm using skll 1.0.1 .

**Comment by desilinguist** [comment] 2015-07-14 21:28
I think support for skll v1.0 and above is coming in the pending PR. You might want to try downgrading to skll v0.27.0 until that PR is merged.

**Comment by desilinguist** [comment] 2022-03-07 15:44
Closing since the issue is outdated.

**Closed as completed by desilinguist** 2022-03-07 15:44 UTC
